//Auth
export const SET_USER = 'SET_USER';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';

//post
export const SET_POSTS = 'SET_POSTS';
export const SET_POST_IMAGE = 'SET_POST_IMAGE';
export const SET_POST_LOADING = 'SET_POST_LOADING';

//SET USERS
export const SET_USERS = 'SET_USERS';

//PROFILE DATA
export const SET_PROFILE_POST_DATA = 'SET_PROFILE_POST_DATA';
export const SET_FOLLOWINGS_COUNT = 'SET_FOLLOWINGS_COUNT';
export const SET_FOLLOWERS_COUNT = 'SET_FOLLOWERS_COUNT';
export const SET_USER_META = 'SET_USER_META';
export const SET_LOADING = 'SET_LOADING';
